version = 1

#Â SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Licensing statement required for GHA tests and linting to pass for only this repository

[[annotations]]
path = [
     ".github/gpg-export/gpg-public-key.asc",
     ".ssh-allowed-signers",
     "src/tag_validate/_version.py"
]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2025 The Linux Foundation"
